#!/usr/bin/env bash
# This is a Bash script that generates a MySQL dump
# and creates a compressed archive out of it.
sudo mysqldump -uroot --password=$1 --all-databases > backup.sql
tar -czvf `date +"%d-%m-%Y.tar.gz"` backup.sql
