#!/bin/bash
# configures ufw firewall
sudo apt install ufw
sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw status verbose
sudo ufw enable
